### ISSUE TITLE
Uncaught Error: Pattern length is too long

### ISSUE THREAD

**Issue by EstEsca** [Stefterv/processing-autocomplete#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [processing-autocomplete](https://github.com/Stefterv/processing-autocomplete) package 0.2.0

### Stack Trace

Uncaught Error: Pattern length is too long

```
At C:\Users\Jsuh\.atom\packages\processing-autocomplete\lib\fuse.js:1

Error: Pattern length is too long
    at /packages/processing-autocomplete/lib/fuse.js:1:927)
    at e.search (/packages/processing-autocomplete/lib/fuse.js:1:3070)
    at Object.getSuggestions (/packages/processing-autocomplete/lib/processing-autocomplete-provider.coffee:49:21)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -2:26 editor:newline (input.hidden-input)
  5x -2:22.8.0 core:backspace (input.hidden-input)
  8x -2:13.9.0 core:move-up (input.hidden-input)
     -2:11.3.0 editor:newline (input.hidden-input)
  7x -2:10.5.0 core:backspace (input.hidden-input)
  2x -2:03.9.0 core:move-right (input.hidden-input)
 26x -2:01.7.0 core:backspace (input.hidden-input)
     -1:38 core:move-up (input.hidden-input)
     -1:38 core:move-right (input.hidden-input)
     -1:37.7.0 core:move-down (input.hidden-input)
     -1:37.4.0 core:move-up (input.hidden-input)
     -1:37.2.0 core:move-down (input.hidden-input)
 35x -1:26.2.0 core:backspace (input.hidden-input)
     -0:37.1.0 editor:newline (input.hidden-input)
 51x -0:36.6.0 core:backspace (input.hidden-input)
     -0:11.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
```

**Comment by EstEsca** [comment]
Well, there was not so serious problem.  I was making a long comment, and I was notified.
